class EVENT_NAMES:
    GOTO_MAIN_MENU = "goto_main_menu"
    ESCAPE = "escape"
    PAUSE_GAME = "pause"
    START_GAME = "start_game"
    GOTO_SETTINGS_MENU = "goto_settings_menu"
    DISPLAY_REVIEW = "display_review"
    SNEAKING = "sneaking"
    RECALCULATE_WAYPOINTS = "update_waypoints"
    FINISH_ORDER = "finish_order"
    ADD_ORDER = "add_order"
    ADD_SCORE = "add_score"
    SHOW_PLAYER_ORDER = "show_player_order"
    HIDE_PLAYER_ORDER = "hide_player_order"
    GAME_VICTORY = "i_know_someone_who_will_never_see_this_because_they_dont_use_consts"
    GAME_OVER = "game_over"
