name: application-build 

on:
  push:
    branches:
      - "main"

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install panda
        run: python3 -m pip install -r requirements.txt

      - name: build
        run: python3 setup.py build_apps 

      - uses: actions/upload-artifact@v3
        with:
          name: Tube_Win
          path: ./build/win_amd64/

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install panda
        run: python3 -m pip install -r requirements.txt

      - name: Install Setuptools
        run: python3 -m pip install setuptools

      - name: build
        run: python3 setup.py build_apps 

      - uses: actions/upload-artifact@v3
        with:
          name: Tube_OSX
          path: ./build/macosx_10_9_x86_64/

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install panda
        run: python3 -m pip install -r requirements.txt

      - name: build
        run: python3 setup.py build_apps 

      - uses: actions/upload-artifact@v3
        with:
          name: Tube_Linux
          path: ./build/manylinux2010_x86_64/ 

  release:
    needs: [build-windows, build-macos, build-linux]
    steps:
      
      - uses: actions/download-artifact@v4
        with:
          path: builds

      - run: zip -r linux_{{ $GITHUB_REF_NAME }}.zip builds/manylinux2014_x86_64
      - run: zip -r windows_{{ $GITHUB_REF_NAME }}.zip builds/win_amd64
      - run: zip -r macos_{{ $GITHUB_REF_NAME }}.zip builds/macosx_10_9_x86_64

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            linux_{{ $GITHUB_REF_NAME }}.zip
            windows_{{ $GITHUB_REF_NAME }}.zip
            macos_{{ $GITHUB_REF_NAME }}.zip
